config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'

  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  delete "/log-out" => "sessions#destroy", as: :log_out

  resources :users

  resources :posts do
    resources :comments
  end

  resources :skills do
    resources :projects, :except => [:index]
  end

  resources :references
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  validates :body, :presence => true
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, :presence => true
  validates :body, :presence => true
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :skill
  validates :name, :presence => true
  validates :description, :presence => true
  validates :link, :presence => true
end

app/models/reference.rb
class Reference < ActiveRecord::Base
  validates :name, :presence => true
  validates :email, :presence => true
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  has_many :projects, dependent: :destroy
  validates :name, :presence => true
  validates :description, :presence => true
end

app/models/skills.rb
class Skills < ActiveRecord::Base
  validates :name, :presence => true
  validates :description, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  validates_confirmation_of :password
  validates :email, uniqueness: true
  before_save :encrypt_password
  has_many :comments, dependent: :destroy

  def encrypt_password
    self.password_salt ||= BCrypt::Engine.generate_salt
    self.password_hash ||= BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(email, password)
    user = User.where(email: email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  include Pundit
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @user = current_user
    @comment = @post.comments.new(comment_params)
    @user.comments.push(@comment)
    if @comment.save
      respond_to do |format|
        format.html { redirect_to post_path(@post) }
        format.js
      end
    else
      redirect_to post_path(@post)
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @skills = Skill.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.sort_by{ |object| [object.created_at] }.reverse
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    authorize @post = Post.new
  end

  def create
    authorize @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Your entry has been successfully added."
      redirect_to posts_path
    else
      flash[:alert] = "Something went wrong with creating your entry. Try again."
      render :new
    end
  end

  def edit
    authorize @post = Post.find(params[:id])
  end

  def update
    authorize @post = Post.find(params[:id])
    authorize @post
    if @post.update(post_params)
      flash[:notice] = "Your entry has been updated."
      redirect_to post_path(@post)
    else
      flash[:alert] = "There was a problem updating your entry. Please try again."
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def show
    @skill = Skill.find(params[:skill_id])
    @project = Project.find(params[:id])
  end

  def new
    @skill = Skill.find(params[:skill_id])
    authorize @project = @skill.projects.new
  end

  def create
    @skill = Skill.find(params[:skill_id])
    authorize @project = @skill.projects.new(project_params)
    if @project.save
      flash[:notice] = "Project successfully added!"
      redirect_to skill_path(@skill)
    else
      render :new
    end
  end

  def edit
    @skill = Skill.find(params[:skill_id])
    authorize @project = Project.find(params[:id])
  end

  def update
    @skill = Skill.find(params[:skill_id])
    authorize @project = Project.find(params[:id])
    if @project.update(project_params)
      flash[:notice] = "Project successfully update!"
      redirect_to skill_project_path(@skill, @project)
    else
      render :edit
    end
  end

  def destroy
    @skill = Skill.find(params[:skill_id])
    authorize @project = Project.find(params[:id])
    @project.destroy
    redirect_to skill_path(@skill)
  end

  def project_params
    params.require(:project).permit(:name, :description, :link, :preview_image)
  end
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
  def index
    @references = Reference.all
  end

  def new
    @reference = Reference.new
  end

  def create
    @reference = Reference.new(reference_params)
    if @reference.save
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
  end

  private
  def reference_params
    params.require(:reference).permit(:name, :email)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "Login success!"
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem logging you in. Please try again."
      redirect_to log_in_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've been logged out successfully."
    redirect_to "/"
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def index
    @skills = Skill.all
  end

  def show
    @skill = Skill.find(params[:id])
  end

  def new
    authorize @skill = Skill.new
  end

  def create
    authorize @skill = Skill.new(skill_params)
    if @skill.save
      flash[:notice] = "Skill successfully added!"
      redirect_to skills_path
    else
      flash[:alert] = "There was a problem adding your skill. Please try again."
      render :new
    end
  end

  def edit
    authorize @skill = Skill.find(params[:id])
  end

  def update
    authorize @skill = Skill.find(params[:id])
    if @skill.update(skill_params)
      flash[:notice] = "Skill successfully updated!"
      redirect_to skill_path(@skill)
    else
      flash[:alert] = "There was a problem updating your skill. Please try again."
      render :edit
    end
  end

  def destroy
    authorize @skill = Skill.find(params[:id])
    @skill.destroy
    redirect_to skills_path
  end

  private
  def skill_params
    params.require(:skill).permit(:name, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.sort_by{ |object| [object.username ] }
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Thank you for signing up!"
      redirect_to "/"
    else
      flash[:alert] = "There was a problem creating your account. Please try again."
      redirect_to :back
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<li>
  <p class="comments"><%= comment.body %></p>
  <p class="muted">Posted by: <%= link_to User.find(comment.user_id).username, user_path(User.find(comment.user_id)) %> on <%= comment.created_at.to_formatted_s(:long) %></p>
</li>
<hr>

app/views/comments/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading text-center">Add a Comment</div>
  <div class="panel-body">
    <%= form_for [@post, Comment.new], remote: true do |f| %>
      <div class="form-group">
        <%= f.text_area :body, hide_label: true, :class => "form-control", :rows => "3", :id => 'Body' %>
      </div>
      <%= f.submit "submit", :class => "center"%>
    <% end %>
  </div>
</div>

app/views/comments/create.js.erb
$('#Body').val('');
$('#comments').append('<%= j render(@comment) %>');

app/views/comments/new.html.erb
<!-- in the case where the user enters in the new comment route -->

<h1>New Comment</h1>

<%= render "form" %>

app/views/home/index.html.erb
<div class="col-sm-6">
  <div class="well front-page">
    <h1>About</h1>
    <p>Hi! My name is Kim Dang and I love programming and making things. This is my personal portfolio with some of the projects I've worked on. I hope you enjoy looking around.</p>
  </div>

  <div class="well front-page">
    <h1>Contact</h1>
    <p><b>Email:</b> kimdangg@gmail.com</p>
    <p><b>Linkedin:</b> <%= link_to "linkedin.com/in/kimdangg", "http://linkedin.com/in/kimdangg" %></p>
    <p><b>Github:</b> <%= link_to "github.com/kimdangg", "http://github.com/kimdangg" %></p>
  </div>
</div>

<div class="col-sm-6">
  <div class="well">
    <h1>Skills</h1>

    <% if @skills.any? %>
      <ul>
        <% @skills.each do |skill| %>
          <li><%= link_to skill.name, skill_path(skill) %></li>
        <% end %>
      </ul>
    <% else %>
      <p>There are no skills.</p>
    <% end %>
  </div>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>--- KD ---</title>
  <link href='https://fonts.googleapis.com/css?family=Quicksand:300,400' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">KD</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav special-color">
          <li><%= link_to 'SKILLS', skills_path %></li>
          <li><%= link_to 'BLOG', posts_path %></li>
          <% if current_user %>
            <li><%= link_to 'LOGOUT', log_out_path, method: :delete, :id => 'logout' %></li>
            <% if current_user.admin? %>
              <li "navbar-right"><%= link_to current_user.username, user_path(current_user) %></li>
            <% end %>
          <% else %>
            <li><%= link_to 'SIGN UP', new_user_path, :id => 'sign-up' %></li>
            <li><%= link_to 'LOGIN', log_in_path, :id => 'login' %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <div class="container">
    <div class="container">
      <%= flash[:notice] %>
      <%= flash[:alert] %>
    </div>
    <%= yield %>
  </div>
</body>
</html>

app/views/posts/_form.html.erb
<div class="well">
  <%= render "layouts/errors", :object => @post %>
  <%= form_for [@post] do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, :class => 'form-control' %><br />
    </div>
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, :class => 'form-control', :rows => "8" %><br />
    </div>
    <%= f.submit "submit", :id => 'submit-post' %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h1>Edit Entry</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1 class="text-center">Blog Entries</h1>

<% if current_user && current_user.admin? %>
  <p class="text-center"><%= link_to "NEW ENTRY", new_post_path %></p>
<% end %>

<% if @posts.any? %>

  <ul class='unstyled-list'>
    <% @posts.each do |post| %>
      <li>
        <div class='well'>
          <p><%= post.created_at.strftime("%B %d, %Y") %></p>
          <p><%= link_to post.title, post_path(post) %></p>
          <p><%= post.body %></p>
        </div>
      </li>
    <% end %>
  </ul>

<% else %>
  <p>There are no blog entries.</p>
<% end %>

app/views/posts/new.html.erb
<h1>New Blog Post</h1>

<%= render "form" %>

app/views/posts/show.html.erb
<div class="well">
  <h4><%= @post.created_at.to_formatted_s(:long) %></h4>
  <h2><%= @post.title %></h2>
  <p><%= @post.body %></p>
</div>

<% if @post.comments.any? %>
<h3>Comments:</h3>
  <div class="well">
    <ul class="unstyled-list" id="comments">
      <% @post.comments.each do |comment| %>
        <%= render (comment) %>
      <% end %>
    </ul>
  </div>
<% end %>

<% if current_user %>
  <%= render 'comments/form' %>
  <% if current_user.admin? %>
    <%= link_to 'Edit', edit_post_path(@post) %> |
    <%= link_to 'Delete', post_path(@post), data: { confirm: "Are you sure?", method: "delete"} %>
    <br><br>
  <% end %>
<% else %>
  <p><%= link_to "Sign in", log_in_path, :id => 'login' %> to add a comment</p>
<% end %>

app/views/projects/_form.html.erb
<div class="well well-form">
  <%= render "layouts/errors", :object => @project %>

  <%= form_for [@skill, @project] do |f| %>
    <div class="form-group">
      <%= f.label :name %><br />
      <%= f.text_field :name, :size => "31" %><br />
    </div>
    <div class="form-group">
      <%= f.label :description %><br />
      <%= f.text_area :description, :cols => "30", :rows => "6" %><br />
    </div>
    <div class="form-group">
      <%= f.label :link %><br />
      <%= f.text_field :link, :size => "31" %><br />
    </div>
    <div class="form-group">
      <%= f.label :preview_image %><br />
      <%= f.text_field :preview_image, :size => "31" %><br />
    </div>
    <%= f.submit %>
  <% end %>
</div>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render "form" %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render "form" %>

app/views/projects/show.html.erb
<h1><%= @project.name %></h1>

<div class="well">
  <p><b>Description:</b> <%= @project.description %></p>
  <a href="http://<%= @project.link %>"><img alt="preview_image" src="<%= @project.preview_image%>"></a>
</div>

<% if current_user && current_user.admin? %>
  <%= link_to 'Edit', edit_skill_project_path(@skill, @project) %> |
  <%= link_to 'Delete', skill_project_path(@skill, @project), data: { confirm: "Are you sure?", method: "delete"} %>
<% end %>

app/views/skills/_form.html.erb
<div class="well well-form">
<%= render "layouts/errors", :object => @skill %>

  <%= form_for @skill do |f| %>
    <div class="form-group">
      <%= f.label :name %><br />
      <%= f.text_field :name, :size => "31" %><br />
    </div>
    <div class="form-group">

      <%= f.label :description %><br />
      <%= f.text_area :description, :cols => "30", :rows => "6" %><br />
    </div>
    <%= f.submit %>
  <% end %>
</div>

app/views/skills/edit.html.erb
<h1>Edit Skill</h1>

<%= render "form" %>

app/views/skills/index.html.erb
<h1 class="text-center">Skills</h1>
<% if current_user && current_user.admin? %>
  <p class="text-center"><%= link_to "NEW SKILL", new_skill_path %></p>
<% end %>

<div class="well">

  <% if @skills.any? %>
    <ul>
      <% @skills.each do |skill| %>
        <li><%= link_to skill.name, skill_path(skill) %></li>
      <% end %>
    </ul>
  <% else %>
    <p>There are no skills.</p>
  <% end %>
</div>

app/views/skills/new.html.erb
<h1>New Skill</h1>

<%= render "form" %>

app/views/skills/show.html.erb
<h1><%= @skill.name %></h1>

  <div class= 'well'>
    <p><b>Description:</b> <%= @skill.description %></p>
  </div>

<h2>Projects</h2>

<div class="well">
  <% if @skill.projects.any? %>
    <ul>
      <% @skill.projects.each do |project| %>
        <li><%= link_to project.name, skill_project_path(@skill, project) %></li>
      <% end %>
    </ul>
  <% else %>
    <p>There are no projects.</p>
  <% end %>

</div>
  <br>

<% if current_user && current_user.admin? %>
  <%= link_to 'Add a Project', new_skill_project_path(@skill) %> |
  <%= link_to 'Edit', edit_skill_path(@skill) %> |
  <%= link_to 'Delete', skill_path(@skill), data: { confirm: "Are you sure?", method: "delete"} %>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.username user_path(user) %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading text-center">Sign Up</div>
    <div class="panel-body">
      <%= bootstrap_form_for @user do |f| %>
        <%= f.text_field :username %>
        <%= f.email_field :email %>
        <%= f.password_field :password %>
        <%= f.password_field :password_confirmation %>
      <%= f.submit "Sign Up", :id => 'new-user' %>
    <%end%>
  </div>
</div>

app/views/users/show.html.erb
<h2><%= @user.username %></h2>